Vagrant.configure("2") do |config|

  # Web01 - Ubuntu 20.04
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/bionic64"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.33.11"
  end

  # Web02 - Ubuntu 20.04
  config.vm.define "web02" do |web02|
    web02.vm.box = "ubuntu/bionic64"
    web02.vm.hostname = "web02"
    web02.vm.network "private_network", ip: "192.168.33.12"
  end

  # DB01 - CentOS 7
  config.vm.define "db01" do |db01|
    db01.vm.box = "centos/7"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.33.13"

    # Provisioning for MariaDB
    db01.vm.provision "shell", inline: <<-SHELL
      sudo yum install -y mariadb-server
      sudo systemctl enable mariadb
      sudo systemctl start mariadb
    SHELL
  end

end

